services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: web-runner
    container_name: kes-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: .env.docker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - kes-net

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker-runner
    container_name: kes-worker
    restart: unless-stopped
    env_file: .env.docker
    environment:
      RUN_MIGRATIONS: "0"

    command: ["node", "apps/web/worker.js"]
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - kes-net

  pgbouncer:
    profiles: ["pooler"]
    image: edoburu/pgbouncer:latest
    container_name: kes-pgbouncer
    restart: unless-stopped
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: kesling_cirebon
      POOL_MODE: transaction
      AUTH_TYPE: plain
      MAX_CLIENT_CONN: 500
      DEFAULT_POOL_SIZE: 20
      RESERVE_POOL_SIZE: 5
      SERVER_RESET_QUERY: DISCARD ALL
    ports:
      - "6432:5432"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - kes-net

  postgres:
    image: postgres:16-alpine
    container_name: kes-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kesling_cirebon
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kes-net

  redis:
    image: redis:7-alpine
    container_name: kes-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kes-net

volumes:
  pgdata:

networks:
  kes-net:
