const fs = require('fs');
let code = fs.readFileSync('/Users/fikri/Aplikasi/apps-kes/apps/web/src/app/(app)/laporan-builder/page.tsx', 'utf-8');

// Fix Save Mutation to handle ID properly
code = code.replace(
  /createMut\.mutate\(\{\\n\\s+id: selectedTemplateId \\|\\| undefined,\\n\\s+nama,\\n\\s+deskripsi,\\n\\s+subCategoryId: subCategoryId \\? Number\\(subCategoryId\\) : null,\\n\\s+fields: \\[\\n\\s+\\.\.\\.metaFields\\.map\\(\\(f, i\\) => \\(\\{\\n\\s+\\.\.\\.f,\\n\\s+\\.\.\\.urutan: i,\\n\\s+\\.\.\\.grup: \\"__META__\\"\\n\\s+\\.\.\\.options: f\.tipe === \\"DROPDOWN\\" \\&\\& f.options \\? f.options.split\\(\\\",\\\\\\\\\"\\).map\\(\\(s: string\\) => s.trim\\(\\)\\n : f.options\\n\\s+\\} ),/g,
  'id: selectedTemplateId ? parseInt(selectedTemplateId, 10) : undefined,\n    nama,\\n      deskripsi,\\n      subCategoryId: subCategoryId ? Number(subCategoryId) : null,\\n      fields: [...metaFields.map((f, i) => ({ ...f, urutan: i, grup: "__META__" })), ...fields.map((f, i) => ({ ...f, urutan: metaFields.length + i, grup: f.grup || "" }))].map((f, i) => ({ ...f, options: f.tipe === \"DROPDOWN\" && f.options ? (typeof f.options === \"string\" ? f.options.split(\",\").map((s: string) => s.trim()) : f.options) : null, urutan: i}))\\n'
);

// Fix save mutation to actually delete first
code = code.replace(
  /mutationFn: async \\(data: any\\) => \\{/, 
  'mutationFn: async (data: any) {\\n    // Ensure we are updating or creating\\n    const existing = selectedTemplateId ? await prisma.inspectionTemplate.findUnique({ where: { id: selectedTemplateId } }) : null;\\n    const fieldsToCreate = [];\\n    if (selectedTemplateId) {\\n      // Delete old fields first\\n      await prisma.inspectionField.deleteMany({ where: { templateId: selectedTemplateId } });\\n    }\\n    return prisma.inspectionTemplate.upsert({\\n      where: { id: selectedTemplateId ? parseInt(selectedTemplateId, 10) : undefined },\\n      update: {\\n        nama: nama,\\n        deskripsi: deskripsi,\\n        subCategoryId: subCategoryId ? Number(subCategoryId) : null,\\n        fields: {\\n          delete: fields.filter(f => f.id),\\n          create: fields.map(f => ({\\n            pertanyaan: f.pertanyaan,\\n            tipe: f.tipe,\\n            isRequired: f.isRequired,\\n            urutan: f.urutan,\\n            grup: f.grup,\\n            options: f.options ? JSON.stringify(f.options) : null\\n          })\\n        }\\n      }\\n    });\\n  },\\n  onSuccess: () => {\\n    queryClient.invalidateQueries({ queryKey: [\\"inspection-templates\\"] });\\n    setOpen(false);\\n    setNama(\\"\\");\\n    setDeskripsi(\\"\\");\\n    setSubCategoryId(\\"\\");\\n    setFields([{ pertanyaan: \"\\\", tipe: \"BOOLEAN\", isRequired: true, grup: \\"\\", options: \\"\\" }]);\\n    toast.success(\\"Form berhasil disimpan\\");\\n  },\\n  onError: (error) => {\\n    toast.error(\"Gagal menyimpan: \" + error.message);\\n  }\\n});\\n\\nfunction handleSave() {\\n  if (!nama) {\\n    toast.error(\"Nama form wajib diisi\");\\n    return;\\n  }\\n  createMut.mutate({\\n    id: selectedTemplateId || undefined,\\n    nama,\\n    deskripsi,\\n    subCategoryId: subCategoryId ? Number(subCategoryId) : null,\\n    fields: [\\n      ...metaFields.map((f, i) => ({ ...f, urutan: i, grup: \"__META__\" })),\\n      ...fields.map((f, i) => ({ ...f, urutan: metaFields.length + i, grup: f.grup || \"\" })),\\n    });\\n  }\\n'
);

fs.writeFileSync('/Users/fikri/Aplikasi/apps-kes/apps/web/src/app/(app)/laporan-builder/page.tsx', code);
