packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@biomejs/biome': true
  '@prisma/client': true
  '@prisma/engines': true
  '@sentry/cli': true
  core-js: set this to true or false
  esbuild: true
  lefthook: true
  prisma: true
  sharp: true
  unrs-resolver: set this to true or false
